dist: trusty
sudo: false
language: php
addons:
  sonarqube:
    token:
      secure: "hKcQzHpVXNNI3pxvlIotHq8ACASUfbs7OLK6ypoUG+XMbPuwUM30Ys2YKbwy52spLifkj10U7PDgXCo6X5oCgTSMHz5bk1WyhBHvoernulcehETDsSFj1ez1dsqkjAjtQk/bazYsfH9lXUVWL/DkkCgkufPSzu0utjPVPP8v8zMa/I9287yCqisJ4gojzNfqxzf5f348UXKuhj1pAgNKHw+Q/4O3noYImmoJurQe05pfzvcFVeEvTsUH0nxWAHKZrhT8KqJvHpCuNeuk4vsq3bq7luko79NG80EwrGia/5WaqhJV0c6vtflPn98LAm8lvJWRUGkZ419Ol7M9ub7eKpGSaQ8kjdEVfzJsdpHWWlIfnEcSZkrYDLuYR2mkdZkWuzM1kdV3Or53x4FddVe5+TXQ+aCqmUanQ2B9Sw9RIrY7vhdM7DLacavlRtwihcZtE8QXF5LTa+8gMEvpaFQsDstk//80xPqdgOow2x95gTDjrirEqILrEPESJKg9NuTNDVP5rxwSSNjoFOSC+36/5cOs/jn8oFMfsnjHkjBn1HNeAnxUj5LPP6Z5ejq6nMdkar7QZqEV4JYqXNEMccMhxTslo0RFPkfFWREzhuf5G3cyzlhJS0HQgjnawv4oRYkDoRH4iUUJJvtLgOq89vaH1Hs6Facth8L5liVPvSnN3X0="

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

env:
  global:
  - COMPOSER_ARGS="--no-interaction"
matrix:
  include:
  - php: 5.6
    env:
    - TEST_COVERAGE=true
  - php: 7
    env:
    - CHECK_CS=true
  - php: 7.1
    env:
    - SONAR_SCAN=true
  - php: hhvm
before_install:
- travis_retry composer self-update
install:
- if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS
  satooshi/php-coveralls:^1.0 ; fi
- travis_retry composer install $COMPOSER_ARGS
- composer show
script:
- if [[ $TEST_COVERAGE == 'true' || ($SONAR_SCAN == 'true' && $TRAVIS_BRANCH == 'master')
  ]]; then composer test-coverage ; else composer test ; fi
- if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi
  - if [[ $SONAR_SCAN == 'true' && $TRAVIS_BRANCH == 'master' ]]; then sonar-scanner ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi

after_success:
- if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then bash generate-docs.sh; fi

deploy:
  provider: releases
  api_key:
    secure: "L/tjXkmvzV4UxiukwcbgaKj7LQacUEKX7hnHV4/FlPnAcalKMikkye25XwxiAAZKXoV1iGMh1kI8QtANsp6HuwH10GzGqOMU5zUXO12AlYfZSEXxaCXAd1qqLEAfR/GtJ/VOcP62TXoxUbWYqMVPEwnZOy+z4W7wwNk5XFbTlY1bCC7HLup5ePWzYgSnZwq37/z0/6OKWMlfLrhIoPMMTV7IwcQK8zZQGO4qDTfqBe9uyZWInaAplHjmI0SsBiWh/9qVVFUyM81lfmgGl6Wdko2nXXS5vR5ia6oQE5NTk6Gz3Z+NCRR9/MFCx5EnIDW5+CYM9f2ti8Kv3y9H/b1kP7C7xiv9NQWQ8M8vuuxDrFqj6kuytSJgBKhCYZXb1EpKeo99Uy8hN6Cm+6OVHRlZQbpOEwkJMBYJ8qliOTAQsgYXDcxCyqIIEy2In1zjN60F2yJYyFLH1Cy8qooWCSbiRgR6u4VwpN/hxDlUkoBXVxV0FJkImso9wWzwWn7krjxCYQ9J0weGi1BkgLC7Xm9RZl6ecy6MfJuyVLMNZTbqwEINfhCJQ9A/Pt+X6PrYzrAjn6hGu64VzsIBuxsg6fyboz1GSUggyVAKInHQXCclBPkXrDzxwQbC5cqSwsqf2IaReIy2bDe/4w2MjIlJMH4DXhsqtMZhVaTRP4LjhJiW3/8="
  file: wirecard-paymentSDK-php-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: wirecard/paymentSDK-php
    tags: true
